### ISSUE TITLE
How to test the fault tolerance of pipeline templates on real machines?

### ISSUE THREAD

**Issue by yyyyyt123** [insujang/oobleck#15]
Hi,

There seems to be no documentation regarding how to test the failover of Oobleck on real machines. I have tried Oobleck training with 4 nodes, each with 2 GPUs (the fault threshold was set to three). However, when I kill the training process on one node. The whole training system failed and exited before reconfiguration complete.

So, I would like to ask, can I use the `kill` command to test the fault tolerance Oobleck systems? Moreover, can you provide some advice or instructions on how to use the Oobleck pipeline template-based recovery on real machines?

**Comment by insujang** [comment]
I'm sorry, but unfortunately for now there is no support for fault tolerance in real machines, but only unit tests-based verification and in-house simulator-based evaluations. I will improve the implementation so that it can be used for real fault tolerance.

Oobleck assumes an entire node fails, not each training process to fail. Killing each training process would have unexpected behavior.

**Comment by fotstrt** [comment]
Hello! Thank you for the great work! I was wondering if there are any updates on this issue :)

**Comment by insujang** [comment]
Hi! Sorry for being late. I am finishing refactoring Oobleck to make it work in real machines, originally planned to release it by the end of March but delayed a little bit. Once #18 is merged it is done.

**Comment by insujang** [comment]
Hi, #18 has just been merged. Please try it with the instructions in README. Please reopen the issue or recreate an issue if you have any questions. Thanks.
